# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=10000),
        ),
    ]
