# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171018_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
